blank_issues_enabled: false
contact_links:
  - name: Questions & ideas (Discussions)
    url: https://github.com/mollybyte/waveform/discussions
    about: For open-ended questions or discussion, please use Discussions instead of an issue.
